name: Some tests on self hosted runners

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
    private-endpoint-tests:
        runs-on: [self-hosted, javi-runner-29842]
        steps:
        - name: Echo runner name
          run: |
            echo "RUNNING"
            uname -a
            dpkg --list | grep linux-image
            hwe-support-status --verbose
            sudo snap install lxd
            lxd init --auto
            lxc launch ubuntu:24.04 ubuntu-config
            sleep 30
            lxc config device override ubuntu-config eth0 limits.priority=10

